#!/bin/bash

set -xe

sed="sed"

this_path="$(cd dirname $0;pwd)"

bash_rc="${this_path}/../.bash_profile"
gitconfig="${this_path}/../.gitconfig"
vimrc="${this_path}/../.vimrc"

function Usage()
{
	echo "usage ./setup [iu]
	i 		Install
	u 		UnInstall
"
}
function Install()
{
	echo "source ${this_path}/psword_cn" >> "${bash_rc}"
	echo "source ${this_path}/export_cn" >> "${bash_rc}"
	echo "source ${this_path}/alias_cn" >> "${bash_rc}"

	# git config
	if [[ -f "${gitconfig}" ]];then
		mv "${gitconfig}" "${gitconfig}.bak"
	fi
	ln "${this_path}/gitconfig" "${gitconfig}"

	# vimrc
	if [[ -f "${vimrc}" ]];then
		mv "${vimrc}" "${vimrc}.bak"
	fi
	ln "${this_path}/vimrc" "${vimrc}"

	source "${bash_rc}"
}

function UnInstall()
{
	# bash_rc
	${sed} -e '/psword_cn/d' -i "${bash_rc}"
	${sed} -e '/alias_cn/d' -i "${bash_rc}"
	${sed} -e '/export_cn/d' -i "${bash_rc}"

	# git config
	if [[ -f "${gitconfig}.bak" ]];then
		mv "${gitconfig}.bak" "${gitconfig}"
	fi

	# vimrc
	if [[ -f "${vimrc}.bak" ]];then
		mv "${vimrc}.bak" "${vimrc}"
	fi
}

############ main ############

if [[ ! "${#@}" = "1" ]];then
    Usage
	exit -1
fi

if [[ ${1} = "i" ]];then
	Install
elif [[ ${1} = "u" ]]; then
	UnInstall
else
    Usage
    exit -1
fi
